name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Install Poetry
          poetry install  # Install project dependencies

      - name: Run linter
        run: |
          poetry run flake8  # Replace 'flake8' with the linter command for your project

      - name: Run Pytest
        run: |
          poetry run pytest  # Replace 'pytest' with the Pytest command for your project

      - name: Test & publish code coverage
        if: github.ref == 'refs/heads/main'  # Adjust the branch condition as needed
        run: |
          poetry run pytest --cov=.
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Publish code coverage to Code Climate
        if: github.ref == 'refs/heads/main'  # Adjust the branch condition as needed
        uses: paambaati/codeclimate-action@v3.2.0
        with:
          coverageCommand: "poetry run pytest --cov=."
          debug: true  # Enable debug mode as needed